services:
  - type: web
    name: jyc.dev
    env: node
    repo: https://github.com/jycouet/jyc.dev
    branch: main
    buildCommand: npm i -g pnpm@9.0.1; pnpm install --production=false; pnpm build
    startCommand: pnpm start
    numInstances: 1
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096
      - key: TZ
        value: utc
      - key: NODE_ENV
        value: production
      - fromGroup: jyc-dev
