services:
  - type: web
    name: jyc.dev
    env: node
    repo: https://github.com/jycouet/jyc.dev
    branch: main
    buildCommand: npm i -g pnpm; pnpm install --production=false; pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 21.2.0
      - key: TZ
        value: utc
      - key: NODE_ENV
        value: production
      - fromGroup: jyc-dev
